name: ticketmodules
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  timeago:
  badges:
  get: 4.6.5
  pigeon: any
  freezed_annotation: any
  json_annotation: ^4.3.0
  percent_indicator: ^3.4.0

  # flutter_localizations: # Add this line
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

